import type { MathSuggestion } from "./autocomplete";

// Names are case-sensitive and match SymPy's expression namespace.
export const builtinSuggestions: MathSuggestion[] = [
    { name: "sin", parameters: ["x"], description: "Sine; angle in radians" },
    { name: "cos", parameters: ["x"], description: "Cosine; angle in radians" },
    { name: "tan", parameters: ["x"], description: "Tangent; angle in radians" },
    { name: "asin", parameters: ["x"], description: "Inverse sine; result in radians" },
    { name: "acos", parameters: ["x"], description: "Inverse cosine; result in radians" },
    { name: "atan", parameters: ["x"], description: "Inverse tangent; result in radians" },
    { name: "sqrt", parameters: ["x"], description: "Principal square root" },
    { name: "exp", parameters: ["x"], description: "Exponential, E raised to x" },
    { name: "log", parameters: ["x", "base (optional)"], description: "Natural logarithm, or logarithm to a specified base" },
    { name: "Abs", parameters: ["x"], description: "Absolute value" },
    { name: "factorial", parameters: ["n"], description: "Factorial of n" },
    { name: "floor", parameters: ["x"], description: "Round down to an integer" },
    { name: "ceiling", parameters: ["x"], description: "Round up to an integer" },
    { name: "simplify", parameters: ["expr"], description: "Simplify an expression" },
    { name: "expand", parameters: ["expr"], description: "Expand products and powers" },
    { name: "factor", parameters: ["expr"], description: "Factor a polynomial" },
    { name: "diff", parameters: ["expr", "variable", "order (optional)"], description: "Derivative; diff(x^3, x, 2) gives 6*x" },
    { name: "integrate", parameters: ["expr", "variable or (variable, lower, upper)"], description: "Indefinite or definite integral; integrate(x^2, (x, 0, 3))" },
    { name: "limit", parameters: ["expr", "variable", "point"], description: "Limit; limit(sin(x)/x, x, 0)" },
    { name: "summation", parameters: ["expr", "(variable, lower, upper)"], description: "Sum terms; summation(k, (k, 1, 10))" },
    { name: "product", parameters: ["expr", "(variable, lower, upper)"], description: "Multiply terms; product(k, (k, 1, 4))" },
    { name: "series", parameters: ["expr", "variable", "point", "order"], description: "Series expansion; series(exp(x), x, 0, 4)" },
    { name: "subs", parameters: ["expr", "symbol or replacement pairs", "value (optional)"], description: "Substitute without assigning: subs(expr, x, 3) or subs(expr, [(x, 3), (y, 4)])" },
    { name: "Matrix", parameters: ["rows or vector entries"], description: "Matrix([[1,2],[3,4]]) or column vector Matrix([1,2,3])" },
    { name: "eye", parameters: ["size"], description: "Identity matrix" },
    { name: "zeros", parameters: ["rows", "columns (optional)"], description: "Zero matrix" },
    { name: "ones", parameters: ["rows", "columns (optional)"], description: "Matrix filled with ones" },
    { name: "diag", parameters: ["entries"], description: "Diagonal matrix; diag(1,2,3)" },
    { name: "det", parameters: ["matrix"], description: "Matrix determinant" },
    { name: "Function", parameters: ['"name"'], description: 'Unknown function for ODEs; y = Function("y")' },
    { name: "dsolve", parameters: ["equation", "function", "ics (optional)"], description: "Solve an ODE; dsolve(ode, y(t), ics={y(0): 2})" },
    { name: "classify_ode", parameters: ["equation", "function (optional)"], description: "List applicable symbolic ODE solution methods" },
    { name: "unit", parameters: ["value", '"unit"'], description: 'Attach calculated units: unit(10, "m/s")' },
    { name: "convert", parameters: ["quantity", '"target unit"'], description: 'Convert compatible units: convert(speed, "km/h")' },
    { name: "magnitude", parameters: ["quantity", '"target unit"'], description: 'Extract a numeric/symbolic value in chosen units, including for plots' },
    { name: "Eq", parameters: ["left", "right"], description: "Create an equation without assigning: Eq(x + y, 5)" },
    { name: "solve", parameters: ["equation or list", "variable or list", "dict=True (optional)"], description: "Symbolic solutions; solve([Eq(x+y,5), Eq(x-y,1)], [x,y], dict=True)" },
    { name: "solveset", parameters: ["equation", "variable", "domain (optional)"], description: "Solution set; solveset(x^2-4, x, domain=S.Reals)" },
    { name: "linsolve", parameters: ["equations", "variables"], description: "Linear system; linsolve([x+y-5, x-y-1], (x,y))" },
    { name: "nonlinsolve", parameters: ["equations", "variables"], description: "Nonlinear system; nonlinsolve([x^2+y^2-5, x-y-1], (x,y))" },
    { name: "nsolve", parameters: ["equation or list", "variable or list", "initial guess"], description: "Find a numerical root near a guess; nsolve(cos(x)-x, x, 1)" },
    { name: "pi", description: "Circle constant π" },
    { name: "E", description: "Euler's number, the natural logarithm base" },
    { name: "I", description: "Imaginary unit; I² = −1" },
    { name: "oo", description: "Positive infinity" },
].map(item => ({ ...item, scope: "builtin" }));
